version: "3"

networks:
    my-test:
        driver: bridge

services: 
    golang:
        build: .
        container_name: "redis-ipcountry-golang"
        tty: true
        volumes:
            - .:/src/app
        networks:
            - my-test
    
    redis:
        image: redis:6.0-rc-alpine
        container_name: "redis-ipcountry-redis"
        ports: 
          - "6379:6379"
        expose:
          - "6379"
        networks:
            - my-test
